In [1]:
import numpy as np

In [2]:
arr_1d=np.array([1, 2,3,4,5,6]) 
arr_1d#This is a 1dimensional array

array([1, 2, 3, 4, 5, 6])

In [3]:
arr_2d=np.array([[1, 2,3], 
                 [4, 5,6]]) 
arr_2d#This is a 2D array/matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr_3d=np.array([[[1, 2,3], 
                  [4, 5,6], 
                  [7, 8,9]]]) 
arr_3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [5]:
zeros=np.zeros(10) 
zeros#This code will return 1D array the element will be zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
zeros_3d=np.zeros((3, 3)) 
zeros_3d#This code will return 3D array the element will be zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
ones=np.ones(10) 
ones#this code will return 1D array. And the element will be one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
one_2d = np.ones((2, 2)) 
one_2d#this will return 2D array. all the element will be 1

array([[1., 1.],
       [1., 1.]])

In [9]:
filled_arr=np.full(10, 7) 
filled_arr#this will return 1d 10 element array all the element will be 7

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [10]:
filled_2d_arr=np.full((2, 2), 10) 
filled_2d_arr#This will return 2d array and all the element will be 10

array([[10, 10],
       [10, 10]])

In [11]:
test_arr=np.arange(1, 10,2) 
test_arr#This code will return 1d array all the element will be odd number

array([1, 3, 5, 7, 9])

In [12]:
identity=np.eye(3) 
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
test_2d=np.array([[1, 2,3], 
                  [4, 5,6]]) 
test_2d.shape#returns the shape of a array

(2, 3)

In [14]:
test_2d.size#returns the size of a array

6

In [15]:
test_2d.ndim#returns the dimenson of a array

2

In [16]:
test_2d.dtype

dtype('int32')

In [17]:
type_arr=np.array([10.0, 20.0,30.0,40.0,50.0,60.0]) 
int_arr=type_arr.astype(int) 
int_arr#convert the datatype of a array's element

array([10, 20, 30, 40, 50, 60])

In [18]:
math_arr=np.array([10, 20,30,40,50,60]) 
print(math_arr+5)#it will plus 5 to all element of the array
print(math_arr-5)#it will minus 5 to all the element of a array
print(math_arr*5) #it will multiply 5 to all the elemtn of a array
print(math_arr/5) #it will devide 5 to all the element of a array

[15 25 35 45 55 65]
[ 5 15 25 35 45 55]
[ 50 100 150 200 250 300]
[ 2.  4.  6.  8. 10. 12.]


In [19]:
print(np.sum(math_arr)) #it will sum all the element of a array

210


In [20]:
print(np.mean(math_arr))#return the avarage of all element of a array

35.0


In [21]:
print(np.max(math_arr)) #return the maximum value of an array

60


In [22]:
print(np.min(math_arr)) #returns the minimum value of a array

10


In [23]:
index_arr=np.array([10, 20,30,40,50,60]) 
print(index_arr[0]) #return the first element of an array

10


In [24]:
print(index_arr[5]) #return the last element of a array

60


In [25]:
print(index_arr[-5]) #return the last element of an array

20


In [26]:
print(index_arr[0:5])#return the 1st to 4th number index element

[10 20 30 40 50]


In [28]:
print(index_arr[:4]) 


[10 20 30 40]


In [31]:
print(index_arr[::2]) #this clde will return odd number 

[10 30 50]


In [32]:
print(index_arr) 

[10 20 30 40 50 60]


In [35]:
filt=(index_arr[index_arr>30]) 
filt#it will filter all the element that are greater than 30

array([40, 50, 60])

In [39]:
rsp_arr=np.array([1, 2,3,4,5,6,]) 
reshaped_arr = rsp_arr.reshape(2, 3) 
reshaped_arr#this will convert 1D array to 2d array

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
rsp_2d=np.array([[1, 2,3], 
                 [4, 5,6]]) 

In [41]:
rsp_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
reshaped_1d_arr=rsp_2d.ravel() 
reshaped_1d_arr#it will convert 2d array to 1d array

array([1, 2, 3, 4, 5, 6])

In [44]:
flaten=rsp_2d.flatten() 
flaten

array([1, 2, 3, 4, 5, 6])

In [45]:
insert_arr=np.array([1, 2,3,4,5,6,7,8,9,0]) 
inserted_arr=np.insert(insert_arr, 2,100,axis=0) 
inserted_arr#it will insert 100 at the index number 2

array([  1,   2, 100,   3,   4,   5,   6,   7,   8,   9,   0])

In [47]:
apd=np.array([10, 20,30,40,50,60]) 
apd_arr=np.append(apd,200) 
apd_arr#it will append 200 at the last index of the array

array([ 10,  20,  30,  40,  50,  60, 200])

In [49]:
ins_2d=np.array([[1, 2,3], 
                 [4, 5,6]]) 
ins_2d_arr=np.insert(ins_2d,2, [7, 8,9,], axis=0)
ins_2d_arr#insert multiple element in a array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
apd_2d=np.array([[1, 2,3,4,5], 
                 [6, 7,8,9,0]]) 
apd_2d_arr=np.append(apd_2d,[11, 12,13,14,15]) 
apd_2d_arr#insert multiple element at the last index of a array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0, 11, 12, 13, 14, 15])

In [57]:
arr1=np.array([1, 2,3,4,5]) 
arr2=np.array([6, 7,8,9,0]) 
con_arr=np.concatenate((arr1, arr2)) 
con_arr#it will add two arrays

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [60]:
del_arr=np.array([1, 2,3,4,5,6,7]) 
delete=np.delete(del_arr, 0) 
delete#it will delete the first element of an array

array([2, 3, 4, 5, 6, 7])

In [62]:
del_2d=np.array([[1,2, 3], 
                 [4, 5,6]]) 
delete_2d_arr=np.delete(del_2d, 0)
delete_2d_arr#delete the first element of an 2d array and return 1d array 

array([2, 3, 4, 5, 6])

In [65]:
new_arr_1=np.array([1, 2,3,4,5,6]) 
new_arr_2=np.array([7, 8,9,10,11,12]) 
print(np.vstack(new_arr_1)) 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [66]:
print(np.vstack(new_arr_2)) 

[[ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [67]:
print(np.hstack(new_arr_1)) 
print(np.hstack(new_arr_2)) 

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]


In [70]:
split_arr=np.array([1, 2,3,4,5,6]) 
print(np.split(split_arr,2)) #it will split the array into 2 arrays

[array([1, 2, 3]), array([4, 5, 6])]


In [71]:
math=np.array([100, 200,300,400,500]) 
result=math*2
result#it will multiply 2 to all the element of the array

array([ 200,  400,  600,  800, 1000])

In [74]:
sum_arr1=np.array([1, 2,3,4,5]) 
sum_arr2=np.array([6, 7,8,9,0]) 
new_sum_arr=sum_arr1+sum_arr2
new_sum_arr#it will add all the element in the 2 arrays

array([ 7,  9, 11, 13,  5])

In [75]:
sum_2d=np.array([[10, 20,30],
                 [40, 50,60]]) 
sum_1d=np.array([10, 20,30]) 
new_sum=sum_2d+sum_1d
new_sum

array([[20, 40, 60],
       [50, 70, 90]])

In [77]:
nan_arr=np.array([1, 2,np.nan, 3,4,np.nan, 6,np.nan, 7,8,np.nan]) 
nan_arr#creating nan arrays

array([ 1.,  2., nan,  3.,  4., nan,  6., nan,  7.,  8., nan])

In [79]:
print(np.isnan(nan_arr))#it will return true when the element will be nan else ruturn false

[False False  True False False  True False  True False False  True]


In [80]:
filled_arr=np.nan_to_num(nan_arr, nan=0) 
filled_arr#it will replace nan value to 0

array([1., 2., 0., 3., 4., 0., 6., 0., 7., 8., 0.])

In [83]:
inf_arr=np.array([1, 2,3,4,np.inf, 6,7,8,-np.inf]) 
inf_arr#to create positive and negative infinity value array

array([  1.,   2.,   3.,   4.,  inf,   6.,   7.,   8., -inf])

In [84]:
print(np.isinf(inf_arr)) 

[False False False False  True False False False  True]


In [85]:
clean_arr=np.nan_to_num(inf_arr, posinf=100, neginf=0) 
clean_arr#it will replace negative infinity with 0 and positive infinity with 100

array([  1.,   2.,   3.,   4., 100.,   6.,   7.,   8.,   0.])